title: "Jeroscope"
description: "0-day Research"
url: "https://jeroscope.com"
theme: null
remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

markdown: kramdown
permalink: /:categories/:title/
paginate: 10
locale: en

include:
  - _pages

minimal_mistakes_skin: "dark"   # 다크 스킨
sass:
  style: compressed